import './styles/globals.css';
import { Inter } from 'next/font/google';
import { BlitzProvider } from './blitz-client';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { title: 'New Blitz App', template: '%s – Blitz' },
  description: 'Generated by blitz new ',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <title>TODO</title>
      </head>
      <body className={inter.className}>
        <BlitzProvider>{children}</BlitzProvider>
      </body>
    </html>
  );
}
